import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
   children,
   }: {
    children: React.ReactNode;
   }) {
  return (
    <html lang="en">
      <body>

        <nav className="flex justify-between p-5 border-b">
          <h1>Ego's Cakes</h1>

          <div className="space-x-4">
            <a href="/">Home</a>
            <a href="/cakes">Cakes</a>
            <a href="/admin/login">Admin</a>
          </div>
        </nav>
        {children}

      </body>
    </html>
  );
}
